export const BASE_URL='https://fakestoreapi.com/'
export const PRODUCTS='products'

export const USER_DATA='user_data'

export const BASE_PAG_URL='https://api.instantwebtools.net/'
export const PASSENGER_DATA='v1/passenger'
export const LOGIN_TYPE='login_type'
export const SOCIAL='social'
export const NORMAL='normal'
export const SUCESS='sucess'
export const ERROR='error'
export const LOADING='loading'
export const SUCCESS='loading'
export const FAILED='failed'
export const IDLE='idle'
